/*
** EPITECH PROJECT, 2021
** libC - Starter
** File description:
** This file was automatically generated by libC starter command.
*/

#include "../include/rpg.h"

int pre_init(int ac, char **av)
{
    if ((ac > 2) || (ac == 2 && !check_args(av, 1, "-h")))
        return (my_error("Error: Type ./my_rpg -h for help.\n", 84));
    if (ac == 2 && check_args(av, 1, "-h"))
        return (my_error(HELP_MESSAGE, 84));
    return (0);
}

int main(int ac, char **av)
{
    game_t game;

    if (pre_init(ac, av) == 84)
        return (84);
    load_assets(&game);
    init_windows(&game);
    btn_init_menu(&game);
    void (*game_ptr[10])(game_t *) =
        {&loop_menu, &loop_play, &init_play_loop, &loop_new_game,
        &init_ng, 0, 0, &loop_setting, &init_slider};
    while (sfRenderWindow_isOpen(game.window))
        (*game_ptr[game.state])(&game);
    first_free(&game);
    return 0;
}